### ISSUE TITLE
Add pronouns to person layout

### ISSUE THREAD

**Issue by jacobwhall** [osmus/dogwood#5]
It would be great to be able to specify someone's pronouns to appear on their person page. I imagine something like this in the YAML frontmatter of a file in the `_people` directory:
```yaml
title: Jacob Hall
pronouns: they/them
website: https://jacobhall.net
```
If the `pronouns` variable is set for someone, their pronouns could appear near their name on their person page.
